### ISSUE TITLE
Troubleshooting help

### ISSUE THREAD

**Issue by OwlTrkr** [at-karan-sharma/autonomous-desk-esphome#1]
I love that I found this as I have been wanting to smarten up my SmartDesk for a while.  I'm new to arduinos, so I'm not sure where to go next.  I got some WROOM 32 (not D) on sale off Amazon.  From what I can find it just has slightly less performance than the 32D.  Same wire pinouts, but paid attention to the labels and should have mine on the right pins.  It will power up off the desk power, connects to HomeAssistant and shows the config, original remote is working on passthrough, but the ESP is not sending/receiving to the desk.  Height readout doesn't update and change commands don't respond.

**Comment by at-karan-sharma** [comment]
Hi @OwlTrkr, thanks for trying out this project. The WROOM 32's [datasheet](https://esp32.com/download/file.php?id=1717) mentions UART support, so it should be compatible. Could you try these steps in order, and share the results? I've run into these issues myself at some point:

1. Is the 10P10C cable fully plugged in on both ends?
2. Are the correct inner wires of the cable tapped into? How does the layout compare to [this cable](/at-karan-sharma/autonomous-desk-esphome/blob/main/images/sinloon-10p10c-cable.jpg)?
3. Are the wires correctly tapping RX & TX? Try shutting off the ESP32, switching the RX/TX cables and trying again.
4. Is the diode oriented correctly?
5. Does the ESP32 work with esphome with a simple config? E.g. try something like [this config](https://community.home-assistant.io/t/esphome-led-switch/536396) to rule out hardware issues.

**Comment by OwlTrkr** [comment]
Thanks for the swift reply.
1. The 10p10c cable I got, https://www.amazon.com/dp/B0B1ZKCRK4, was identical.
2. I cut the cable in half to save length, and connected only the important wires.  So the taps have to be right for that part for the original remote to still work.
3. I could probably swap the 16 and 17 in the config to test swapping the RX and TX too?
4. On thinking the diode might actually be the problem.  It is oriented dark end toward the ESP, but I put shrink tubing over it before thinking.  I might have torched the poor thing.

**Comment by OwlTrkr** [comment]
Ha! Two things that fixed it that I probably just needed to sleep.  Swapping the diode was probably a good idea, the other was that I think the first version of the YAML I sent had the wrong TX/RX pins assigned, and it wouldn't install new ones over wifi.  Had to plug it in to update.  It works!!

**Comment by OwlTrkr** [comment]
OK, new one now that I have it working.  When the "Jump To Memory Preset" is selected for a height and the desk starts moving, the selection returns to N/A after a moment, and the desk stops prematurely, as though another button was pressed that cancels the move.

Looking at the desky.YML, I think it's the line 244-258 section, that 2s delay is not enough for the module to recognize the desk is moving, or the sensor value is not right.

**Comment by OwlTrkr** [comment]
Working kludge in place.  I forked and increased that 2s delay to 15s, to cover the longest distance my presets have.  Works perfectly!

**Comment by at-karan-sharma** [comment]
Glad you got it working :)

It does indeed sound like a movement detection issue. If you have time, feel free to add [debug statements](https://esphome.io/components/logger.html) to confirm if `desk_moving` is still false after 2s.

Increasing the delay should fix it, but ideally, we'd minimize the constant duration for which NOOPs are emitted. E.g. with a 15s delay: suppose you jump between 2 nearby height presets in 5s, the integration will continue sending NOOPs for 10 more seconds, which could interfere with keypad commands.
